### ISSUE TITLE
Passing desktop parameter throws error on Windows 11

### ISSUE THREAD

**Issue by vikashraghavan** [SuperflyJon/FileStarter#4]
My json file:

"process": "notepad",
"desktop": 2

Notepad opens in the current desktop instead of desktop 2 (it's already open) and the below error occurs repeatedly 

![image](https://user-images.githubusercontent.com/48412820/132949625-043658e1-d087-40b2-9075-c201782d8772.png)

**Comment by SuperflyJon** [comment]
I wonder what version of windows you have - can you run the "winver" command and let me know?

**Comment by vikashraghavan** [comment]
Sorry, forgot to mention it. 
windows 11
Version 21H2
Build 22000.184

**Comment by SuperflyJon** [comment]
I think MS have made some changes to multiple desktops for windows 11, seemingly breaking their own API in terms of backward compatibility.  Hopefully the script that this project uses will get updated but the link is no longer working which isn't a great sign...

I won't be able to take a look to see if I can fix it until I get windows 11 on one of my machines, which will be at least a few weeks.

**Comment by vikashraghavan** [comment]
Any updates?

**Comment by SuperflyJon** [comment]
No - tried to install windows 11 on one machine and it said it didn't meet the requirements.  Probably need to mess around with secureboot or something in the bios...

**Comment by alper-guven** [comment]
There is a solution.

I found the source of the virtual desktop script. It's not missing.

**VirtualDesktop** is not actively maintained. Since it's not maintained, you will get the same error with this repo or maybe you will get more errors. It's original repo is: [https://github.com/Grabacr07/VirtualDesktop](url) 

But another project (**PSVirtualDesktop**) (which I think the original source of the script used in **FileStarter**, I mean the script at the broken link) has a solution for this issue and it has been already solved (See:  [https://github.com/MScholtes/TechNet-Gallery/tree/master/VirtualDesktop#update-29](url) ). This project actually uses **VirtualDesktop** but they continue to further development of **VirtualDesktop** in their project (not in the original repo of **VirtualDesktop**) since it is not maintained anymore. See the repo: [https://github.com/MScholtes/TechNet-Gallery/tree/master/VirtualDesktop](url)

I haven't tried it yet.

@SuperflyJon Can you implement it to FileStarter? :)

**Comment by SuperflyJon** [comment]
Good work tracking down that file!  I've given it a quick look + test and it works fine (on windows 10), so I've updated the file in this repository.

Give it a go on windows 11 and let me know if that has fixed things.

**Comment by zockie192** [comment]
> Good work tracking down that file! I've given it a quick look + test and it works fine (on windows 10), so I've updated the file in this repository.
> 
> Give it a go on windows 11 and let me know if that has fixed things.

It's working well now with Windows 11 bro
